### ISSUE TITLE
ALA Biosecurity Hub page

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/home-static#2]
Implementation of ALA biosecurity hub page as a subdomain of ALA.

Link to more detailed [Work Package](https://csiroau.sharepoint.com/:w:/r/sites/AtlasofLivingAustralia/_layouts/15/Doc.aspx?sourcedoc=%7B72466BE0-023C-4576-8A11-713CCFC228F4%7D&file=Biosecurity_Hub_page_WP.docx&action=default&mobileredirect=true)

- Static HTML content coming from Transit Graphics (TBA delivery, possible end of Jan)
- Wordpress blocks OR ALA subdomain options (if subdomain, with a test page too)

**Comment by matthewandrews** [comment]
This is in production now (static page, with its own repo, handled similarly to commonui, i.e. hosted on home test/prod instances with nginx vhost)
